FROM ubuntu:latest
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential curl python3-pip
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ffmpeg libsm6 libxext6
WORKDIR /root
RUN git clone https://github.com/MizzouCERI-research/mito_seg_pipeline.git
WORKDIR /root/mito_seg_pipeline
RUN pip3 install -r requirements.txt


